
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL = "https://github.com/MehVahdJukaar/heartstone/issues"


[[mods]] #mandatory

    modUrl = "https://www.curseforge.com/minecraft/mc-mods/heartstone"

    modId= "heartstone" #mandatory

    version = "${version}"

    displayName="Heartstone" #mandatory

    logoFile="icon.png" #optional

    credits="MehVahdJukaar, Plantkillable" #optional

    authors="MehVahdJukaar, Plantkillable" #optional

    description='''
    A magic gem to find the ones that matter
    '''

[modproperties.heartstone]
    catalogueItemIcon = "heartstone:heartstone" #catalogue icon
    configuredBackground = "minecraft:textures/block/amethyst_block.png"


[[dependencies.heartstone]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.heartstone]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heartstone]]

    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.1.21,]"
    side="BOTH"
